# PostgreSQL. Versions 7.4 and 8.x are supported.
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: shopit_development
  pool: 5
  username: shopit
  password: happy_shopper

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: shopit_test
  pool: 5
  username: shopit
  password: happy_shopper

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: shopit_production
  pool: 5
  username: shopit
  password: happy_shopper
